// app/components/Menu.tsx
import { useState } from "react";

export default function Menu(props: any) {
  return (
    <nav className="menu absolute flex left-1/2 -translate-x-1/2 text-white -translate-y-1/2 z-[2]">
        <ul className="flex text-black text-center items-center">
            <li><a href="/">Accueil</a></li>
            <li><a href="/a-propos">À propos</a></li>
            <li><a href="/evaluation">Évaluation maison</a></li>
            <li><a href="/contact">Contact</a></li>
            <li><a href="/calculatrice">Calculatrice</a></li>
            <li><a href="/immobilier">Immobiliére</a></li>
        </ul>
    </nav>
  )
}

// layouts/Menu.vue
<template>
  <nav class="menu translate-y-2/3 z-[2] flex">
    <ul class="flex text-black text-center items-center">
      <li>
        <NuxtLink to="/">Accueil</NuxtLink>
      </li>
      <li>
        <NuxtLink to="/a-propos">À propos</NuxtLink>
      </li>
      <li>
        <NuxtLink to="/evaluation">Évaluation maison</NuxtLink>
      </li>
      <li>
        <NuxtLink to="/contact">Contact</NuxtLink>
      </li>
      <li>
        <NuxtLink to="/calculatrice">Calculatrice</NuxtLink>
      </li>
      <li>
        <NuxtLink to="/immobilier">Immobiliére</NuxtLink>
      </li>
    </ul>
  </nav>
</template>

<style scoped>
.menu {
  border: 2px solid black;
  border-radius: 50px 50px 50px 50px;
}

.menu li {
  display: flex;
  align-items: center;
  padding: 20px 20px;
  transition:
    background-color 0.5s,
    color 0.5s;
  border: 2px solid white;
  color: black;

  height: 100%;
}

.menu li:hover {
  background-color: black;
  color: white;
}

.menu li {
  list-style: none;
  background-color: white;
}

.menu li:last-child {
  padding-right: 40px;
  border-radius: 0px 50px 50px 0px;
}

.menu li:first-child {
  padding-left: 40px;
  border-radius: 50px 0px 0px 50px;
}
</style>
