// pages/contact/index.vue
<template>
  <Section
    :style="{
      backgroundImage: `url(${bgImage})`,
      backgroundPosition: 'center',
      backgroundSize: '100%',
    }"
  >
  </Section>
  <Section class="py-[60px]">
    <div class="w-full flex flex-col items-center text-white">
      <div class="p-8 flex flex-col gap-4">
        <Titre>Vous voulez plus d'information?</Titre>
        <form action="" class="formulaire flex flex-col w-full gap-5">
          <div class="flex gap-6">
            <span class="flex flex-col">
              <label for="prenom"
                >Prénom: <br />
                <input id="prenom" name="prenom" type="text"
              /></label>
            </span>
            <span class="flex flex-col">
              <label for="nom"
                >Nom: <br />
                <input id="nom" name="nom" type="text"
              /></label>
            </span>
          </div>
          <div class="flex gap-6">
            <span class="flex flex-col">
              <label for="prenom"
                >Courriel: <br />
                <input id="prenom" name="prenom" type="text"
              /></label>
            </span>
            <span class="flex flex-col">
              <label for="telephone"
                >Téléphone: <br />
                <input id="telephone" name="telephone" type="text"
              /></label>
            </span>
          </div>
          <div class="flex gap-6">
            <span class="flex flex-row gap-4">
              <label class="form-control" for="f_matin"
                ><input id="f_matin" name="matin" type="checkbox" />
                Matin</label
              >
              <label class="form-control" for="f_midi"
                ><input id="f_midi" name="midi" type="checkbox" /> Après
                midi</label
              >
              <label class="form-control" for="f_soir"
                ><input id="f_soir" name="soir" type="checkbox" /> Soir</label
              >
              <label class="form-control" for="f_finSemaine"
                ><input id="f_finSemaine" name="finSemaine" type="checkbox" />
                Fin de semaine</label
              >
            </span>
          </div>
          <label for="message"
            >Message: <br />
            <textarea
              id="message"
              class="w-full min-h-[120px]"
              name="message"
            />
          </label>
          <Button class="self-start" type="submit">Envoyer message</Button>
        </form>
      </div>
    </div>
    <div class="w-full p-8 flex flex-col gap-4 justify-center items-center">
      <Titre>Contactez-moi</Titre>
      <span class="flex items-center"
        ><img
          alt="phone"
          class="pe-2"
          src="../../assets/images/phone_icon.png"
          width="40"
        />514-142-4254</span
      >
      <span class="flex items-center"
        ><img
          alt="email"
          class="pe-2"
          src="../../assets/images/mail_icon.png"
          width="40"
        />tristanbarbeau@gmail.com</span
      >
      <img
        alt=""
        class="w-[500px] py-6"
        src="../../assets/images/house-banner.jpg"
      />
    </div>
  </Section>
</template>
<script lang="ts" setup>
import Section from "~/components/elements/Section.vue";
import bgImage from "assets/images/Maison_de_bord.png";
import Titre from "~/components/elements/Titre.vue";
import Button from "~/components/elements/Button.vue";
</script>

// app/(routes)/contact/page.tsx
import Section from "../../components/Section";

import React,{ useState, useEffect } from "react";
export default function Contact() { 
    return(
        <main>
            <Section bgStyle={{ height: '400px', minHeight: '0px' }} sectStyle={{ minHeight: '0px' }}>
                <img src="./assets/Maison_de_bord.png" className="max-h-[400px] w-full object-cover" alt="Maison sur le bord" />
            </Section>
            <Section bgStyle={{ backgroundColor: "black"}} sectStyle={{ flexDirection: 'row', alignItems: 'start', padding: '4rem 0' }}>
            <div className="w-full flex flex-col items-center text-white">
                <div className="p-8 flex flex-col gap-4">
                    <h2 className="uppercase self-start text-3xl font-semibold border-s-2 border-primary ps-8">Vous voulez plus d'information?</h2>
                    <form action="" className="formulaire flex flex-col w-full gap-5">
                    <div className="flex gap-6">
                        <span className="flex flex-col">
                        <label htmlFor="prenom">Prénom: <br/>
                        <input type="text" name="prenom" id="prenom"
                        /></label>
                        </span>
                        <span className="flex flex-col">
                        <label htmlFor="nom">Nom: <br/>
                        <input type="text" name="nom" id="nom"/></label>
                        </span>
                    </div>
                    <div className="flex gap-6">
                        <span className="flex flex-col">
                        <label htmlFor="prenom">Courriel: <br/>
                        <input type="text" name="prenom" id="prenom"/></label>
                        </span>
                        <span className="flex flex-col">
                        <label htmlFor="telephone">Téléphone: <br/>
                        <input type="text" name="telephone" id="telephone"/></label>
                        </span>
                    </div>
                    <div className="flex gap-6">
                        <span className="flex flex-row gap-4">
                        <label htmlFor="f_matin" className="form-control"><input type="checkbox" name="matin" id="f_matin" /> Matin</label>
                        <label htmlFor="f_midi" className="form-control"><input type="checkbox" name="midi" id="f_midi" /> Après midi</label>
                        <label htmlFor="f_soir" className="form-control"><input type="checkbox" name="soir" id="f_soir" /> Soir</label>
                        <label htmlFor="f_finSemaine" className="form-control"><input type="checkbox" name="finSemaine" id="f_finSemaine" /> Fin de semaine</label>
                        </span>
                    </div>
                    <label htmlFor="message">Message: <br/>
                        <textarea name="message" className="w-full min-h-[120px]" id="message"/></label>
                    <input type="submit" className="btn-primal self-start bg-primary" value="Envoyer message" />      
                    </form>
                </div>
                </div>
                <div className="w-full p-8 flex flex-col gap-4">
                    <h2 className="uppercase self-start text-3xl font-semibold border-s-2 border-primary ps-8 mb-6">Contactez-moi</h2>
                    <span className="flex items-center"><img src="./assets/phone_icon.png" alt="phone" width={40} className="pe-2" />514-142-4254</span>
                    <span className="flex items-center"><img src="./assets/mail_icon.png" alt="email" width={40} className="pe-2" />tristanbarbeau@gmail.com</span>
                    <img src="./assets/house-banner.jpg" className="w-[500px] py-6" alt="" />
                </div>
            </Section>
        </main>
    )
}
