// pages/evaluation/index.vue
<template>
  <Section class="">
    <div class=" py-8 w-full flex flex-col items-center text-white justify-center">
      <div class="p-8 flex flex-col gap-4">
        <Titre>Vous voulez plus d'information?</Titre>
        <form action="" class="formulaire flex flex-col w-full gap-5">
          <span class="flex flex-col ">
            <label for="telephone"
            >Adresse de votre propriété:<br/>
              <input id="telephone" v-model="adresse" class="w-full" name="telephone" type="text"
              /></label>
          </span>
          <span class="flex flex-col ">
            <label for="nom"
            >Votre nom complet:<br/>
              <input id="nom" v-model="nom" class="w-full" name="nom" type="text"
              /></label>
          </span>
          <span class="flex flex-col ">
            <label for="telephone"
            >Téléphone:<br/>
              <input id="telephone" v-model="phone" class="w-full" name="telephone" type="text"
              /></label>
          </span>
          <span class="flex flex-col ">
            <label for="courriel"
            >Courriel: <br/>
              <input id="courriel" v-model="email" class="w-full" name="courriel" type="text"
              /></label>
          </span>
          <Button class="self-start" type="submit">Envoyer message</Button>
        </form>
      </div>
    </div>
    <NuxtImg alt="Maison avec voiture" class="p-0 m-0 max-h-[700px] object-cover w-full"
             src="assets/images/jane-palash-KnXDtTbcZ8g-unsplash.webp"
             width="1356"/>
  </Section>
</template>
<script lang="ts" setup>
import Section from "~/components/elements/Section.vue";
import Titre from "~/components/elements/Titre.vue";
import Button from "~/components/elements/Button.vue";

let nom = "";
let email = '';
let phone = "";
let adresse = "";


let isSent = ref(false);
const sendMessage = (e: any) => {
  const form = document.querySelector('.formulaire');
  isSent.value = !isSent.value;

  fetch("http://localhost:3020/mailEvaluation", {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      email: email,
      name: nom,
      phone: phone,
      adresse: adresse,
    })
  }).then(res => res.json())
      .then(res => console.log(res));
}
</script>

<style scoped>
.messageSent {
  display: none;
}
</style>

// app/(routes)/evaluation/page.tsx
import Section from "../../components/Section";

export default function Evaluation() { 
    return(
        <Section bgStyle={{ backgroundColor: "black" }} sectStyle={{ flexDirection: 'row', position: 'relative'}}>
        <div className="w-full flex flex-col items-center text-white">
          <div className="p-24 flex flex-col gap-4">
            <h1 className="text-3xl font-semibold uppercase border-s-2 ps-6">Contactez-moi</h1>
            <h3 className='text-lg'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda dolore enim iste natus placeat possimus ratione sed sint sit vitae!</h3>
            <form action="" className="formulaire flex flex-col w-full gap-5">
              <span className='flex flex-col'>
              <label htmlFor="prenom">Adresse de la propriété:</label>
                <input type="text" name="prenom" id="prenom" />
              </span>
              <span className='flex flex-col'>
              <label htmlFor="prenom">Votre nom:</label>
                <input type="text" name="prenom" id="prenom" />
              </span>
              <span className='flex flex-col'>
              <label htmlFor="prenom">Téléphone:</label>
                <input type="text" name="prenom" id="prenom" />
              </span>
              <span className='flex flex-col'>
              <label htmlFor="prenom">Courriel:</label>
                <input type="text" name="prenom" id="prenom" />
              </span>
              <label htmlFor="message">Message: <br/>
                <textarea name="message" className="w-full min-h-[120px]" id="message"/></label>
              <input type="submit" className="btn-primal self-start bg-primary" value="Envoyer message" />      
            </form>
          </div>
        </div>
        <div className="w-full flex justify-center">
          <img src="./assets/jane-palash-KnXDtTbcZ8g-unsplash.png" alt="Banniere maison image" className="object-cover w-full max-h-[1000px]"/>
        </div>
        </Section>
    )
}
